### ISSUE TITLE
The access token verifications to be perfomed by the RS should be described 

### ISSUE THREAD

**Issue by Denisthemalice** [ietf-wg-gnap/gnap-resource-servers#30]
In section 1.4, the text states:

> (7) The RS determines if the token is sufficient for the request by examining the token. The means of the RS determining 
this access are out of scope of this specification, but some options are discussed in [I-D.draft-ietf-gnap-resource-servers].

In I-D.draft-ietf-gnap-resource-servers, Section 3.3. Token Introspection states that "The response MAY include any fields defined in an access token response" which is not helpful for interoperability purposes.

The general treatment of an access token by a RS should be described, otherwise it will be impossible to demonstrate
 or to verify that the GNAP framework **_(which is currently far away from an interoperable protocol_**) is secure.

**Comment by Denisthemalice** [comment]
I don't understand why **_jricher_** has moved this issue from the core document to the second document.
It should be moved back to the core document.

The concern is that the core document is currently only a framework whereas it should describe interoperable protocols. 
The primary goal of the IETF is to describe **_interoperable protocols_**. 

Access token validation and verification shall be able to be done by the RPs without the need to call back the issuing AS.

**Comment by jricher** [comment]
@Denisthemalice the RS document (this document) describes RS behavior including introspection and other forms of interoperable token validation, including ones that require no calls back to the AS. None of this has any bearing on the interoperable behavior of the client instance, which is the focus of the core document.

**Comment by Denisthemalice** [comment]
**@jricher** and **@aaronpk** : The RS document is or was supposed to describe _**optional**_ protocols between the RS and the AS. 

The current text of the introduction clearly states what is not covered by the core document and hence will be covered in this document:

> The core GNAP protocol does not define any one specific mechanism for the resource server (RS) to communicate with the authorization server (AS), allowing the connection between these components to be solved orthogonally to the core protocol's concerns

If the core document were limited to the client and the AS protocols then we would only have one half of the picture 
and the server document would no longer be optional. 

Thus I disagree with **jricher** what he states that interoperable token validation requiring no calls back to the AS should be covered in this document.  

A key issue is whether the GNAP core is a framework or is able to define at least one interoperable protocol. 
The main reason of the existence of the IETF is to define **interoperable protocols**

**Comment by jricher** [comment]
As stated in the agreed upon group charter and the specification documents themselves, GNAP defines a protocol not a framework. The core document does create an interoperable protocol for a well defined set of interoperability. It's not the interoperability that you are personally asking for, but that doesn't mean it's interoperable. You can have interoperability at different levels. Two applications can speak over TCP and be interoperable at that level, but speak HTTP and FTP on top of that and therefore not be interoperable. Would you then say that TCP is not interoperable? Or you can have two different HTTP-based applications with two different APIs that aren't interoperable -- would you say that HTTP is not an interoperable protocol? 

Well-defined interoperable protocols put clear boundaries on what interoperabilities they defined and depend on. GNAP is doing this by focusing the core document on the client-facing pieces and putting several important items -- such as understanding the contents of the access token -- outside of the client's view. This is what makes it interoperable for the client. The RS-focused draft defines things that make the protocol interoperable from the RS's perspective, and since the RS needs to know what to do to interpret the incoming access tokens, that's where this information goes.

As it seems clear now that the purpose of this issue is not to push for clarity on interoperable access token verification methods, which is already the focus of the RS document, but instead to push for a completely different architecture which has not been agreed on by the working group, this issue will be closed.
